In [1]:
# Import library
import os
import sys

# Gets directory where script was launched from
script_dir = os.getcwd()  
script_dir = script_dir + "/../lib/"
print(f"VSA Library: {script_dir}")

# Add the directory to Python's search path
sys.path.append(script_dir)  

import vsa
import numpy as np

VSA Library: /users/micas/rantonio/no_backup/kul_main/pytoy/vsa/../lib/


In [2]:
# Make codebooks and starting HVs
dimension = 1024

A = np.zeros((3,dimension))
B = np.zeros((3,dimension))
C = np.zeros((5,dimension))
D = np.zeros((5,dimension))

for i in range(3):
    A[i] = vsa.gen_hv(dimension, type='bipolar')
    B[i] = vsa.gen_hv(dimension, type='bipolar')

for i in range(5):
    C[i] = vsa.gen_hv(dimension, type='bipolar')
    D[i] = vsa.gen_hv(dimension, type='bipolar')

print(f'A.shape: {np.shape(A)}')
print(f'B.shape: {np.shape(B)}')
print(f'C.shape: {np.shape(C)}')
print(f'D.shape: {np.shape(D)}')
print(f'A sample: {A}')

A.shape: (3, 1024)
B.shape: (3, 1024)
C.shape: (5, 1024)
D.shape: (5, 1024)
A sample: [[ 1.  1.  1. ...  1. -1. -1.]
 [ 1.  1. -1. ...  1. -1. -1.]
 [ 1.  1.  1. ... -1. -1.  1.]]


In [3]:
# Create a combination
bundled_hv_group = [
    vsa.hv_mult_list([A[0],B[0],C[3],D[4]]),
    vsa.hv_mult_list([A[1],B[2],C[2],D[2]]),
    vsa.hv_mult_list([A[2],B[1],C[3],D[3]]),
]

hv_bundled = np.array(vsa.hv_add(bundled_hv_group, sign_magnitude=True))

np.shape(hv_bundled)

(1024,)

In [4]:
# Estimators
num_iter = 50
a = np.zeros((num_iter,dimension))
b = np.zeros((num_iter,dimension))
c = np.zeros((num_iter,dimension))
d = np.zeros((num_iter,dimension))

# Initialize guesses
a[0] = np.sign(np.sum(A, axis=0))
b[0] = np.sign(np.sum(B, axis=0))
c[0] = np.sign(np.sum(C, axis=0))
d[0] = np.sign(np.sum(D, axis=0))

In [5]:
print(a[0])
print(np.sum(a[0]))

[ 1.  1.  1. ...  1. -1. -1.]
36.0


In [6]:
# Create query
hv_query = vsa.hv_mult(hv_bundled, A[0])

print(hv_query)

[-1.  1. -1. ...  1.  1.  1.]


In [7]:
# Iterate a few times only
for i in range(num_iter-1):
    b[i+1] = np.sign(np.matmul(B.T,np.matmul(B, np.array([vsa.hv_mult_list([hv_query, c[i], d[i]])]).T)).T)
    c[i+1] = np.sign(np.matmul(C.T,np.matmul(C, np.array([vsa.hv_mult_list([hv_query, b[i], d[i]])]).T)).T)
    d[i+1] = np.sign(np.matmul(D.T,np.matmul(D, np.array([vsa.hv_mult_list([hv_query, b[i], c[i]])]).T)).T)

In [8]:
for i in range(num_iter):
    print(f'{vsa.hv_cos(B[0],b[i])},{vsa.hv_cos(B[1],b[i])},{vsa.hv_cos(B[2],b[i])}')

0.51953125,0.513671875,0.486328125
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.033203125,0.005859375
1.0,0.0332031

In [9]:
for i in range(num_iter):
    print(f'{vsa.hv_cos(C[0],c[i])},{vsa.hv_cos(C[1],c[i])},{vsa.hv_cos(C[2],c[i])},{vsa.hv_cos(C[3],c[i])},{vsa.hv_cos(C[4],c[i])}')

0.39453125,0.400390625,0.41015625,0.3515625,0.31640625
-0.162109375,0.08984375,0.119140625,0.908203125,0.068359375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,1.0,-0.0234375
-0.0703125,-0.001953125,0.02734375,

In [10]:
for i in range(num_iter):
    print(f'{vsa.hv_cos(D[0],d[i])},{vsa.hv_cos(D[1],d[i])},{vsa.hv_cos(D[2],d[i])},{vsa.hv_cos(D[3],d[i])},{vsa.hv_cos(D[4],d[i])}')

0.388671875,0.419921875,0.3828125,0.330078125,0.4140625
0.15253296519550805,0.017639866723290046,-0.10480156112072321,0.17743630645191752,0.9411387716484748
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.029296875,0.021484375,0.015625,0.052734375,1.0
0.02929687

# Notes:

- This is a partially working resonator network where codebooks A, B, C, and D have fixed sizes.
- It atually works and converges immediately but only under very strict conditions
  - The code books need to be "completely specified" meaning that the combinations are given explicitly
  - The encoded HVs need to be unique. Haven't tested if there are some similarities between the two.
